#!/usr/bin/env python3
"""desktop_privacy.py — the desktop part of the Capture, Admin and Viewer privacy pages.

The desktop applications (Windows, macOS, Linux) show their own privacy text:
no camera, no location permission, no iOS Keychain. Its wording lives ONCE in
hecate-meta, `docs/specs/legal/<lang>.md`, section "Datenschutz — Desktop"
(licensing.md LG5, owner's decision 2026-09-29). This tool copies that section
verbatim into the privacy pages, between two markers, so the site cannot say
something about the desktop that the applications do not.

A block tagged with a role — `(Capture)`, `(Admin)`, `(Viewer)` — goes to that
role's page only. For the Viewer, a `(Viewer)` block also REPLACES the untagged
block with the same key: the Viewer reads and publishes nothing, so the shared
"where data goes" is not its text (ADR 032 §5). The desktop Viewer's page has
no mobile part; the whole page around the block is written by hand.

    python3 tools/desktop_privacy.py            # rewrite the marked blocks
    python3 tools/desktop_privacy.py --check    # report staleness, write nothing

Reads hecate-meta from `HECATE_META` or `../hecate-meta`. The pages keep their
addresses (WS2-1); the block goes in front of the "Children" section.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
META = Path(os.environ.get("HECATE_META", ROOT.parent / "hecate-meta"))
PAGES = ROOT / "docs" / "hecate" / "privacy"
# site suffix, spec file
LANGS = [("", "en"), (".de", "de"), (".fr", "fr"), (".es", "es")]
ROLES = {"capture": "Capture", "admin": "Admin", "viewer-desktop": "Viewer"}
TITLE = {
    "en": "Desktop application (Windows, macOS, Linux)",
    "de": "Desktop-Anwendung (Windows, macOS, Linux)",
    "fr": "Application de bureau (Windows, macOS, Linux)",
    "es": "Aplicación de escritorio (Windows, macOS, Linux)",
}
CHILDREN = re.compile(r"^## (Children|Kinder|Enfants|Menores)\s*$", re.M)
START = "<!-- desktop-privacy:start — generated by tools/desktop_privacy.py from hecate-meta docs/specs/legal/{lang}.md; edit there, not here -->"
END = "<!-- desktop-privacy:end -->"
BLOCK = re.compile(r"\n?<!-- desktop-privacy:start.*?<!-- desktop-privacy:end -->\n\n?", re.S)


def desktop_blocks(lang: str) -> list[tuple[str, str | None, str | None, str]]:
    """(key, role or None, heading or None, body) of the spec's desktop privacy section."""
    text = (META / "docs" / "specs" / "legal" / f"{lang}.md").read_text(encoding="utf-8")
    start = re.search(r"^## .*\(`privacy\.\*`", text, re.M)
    if start is None:
        sys.exit(f"desktop-privacy: no desktop privacy section in {lang}.md")
    rest = text[start.end():]
    stop = re.search(r"^## ", rest, re.M)
    section = rest[: stop.start()] if stop else rest
    blocks = []
    for match in re.finditer(r"^### (.*?) — `([a-z.]+)`(?: \(([A-Za-z]+)\))?\s*$", section, re.M):
        heading, key, role = match.group(1), match.group(2), match.group(3)
        body_start = match.end()
        following = re.search(r"^### ", section[body_start:], re.M)
        body = section[body_start: body_start + following.start()] if following else section[body_start:]
        # "**Überschrift:** …" repeats the heading for the apps; the page has one.
        body = re.sub(r"^\*\*[^*]+:\*\* .*\n", "", body.strip() + "\n", flags=re.M).strip()
        blocks.append((key, role, None if key == "privacy.intro" else heading, body))
    if not blocks:
        sys.exit(f"desktop-privacy: the desktop section of {lang}.md has no blocks")
    return blocks


def render(lang: str, role: str) -> str:
    lines = [START.format(lang=lang), "", f"## {TITLE[lang]}", ""]
    blocks = desktop_blocks(lang)
    own = {key for key, block_role, _, _ in blocks if block_role == ROLES[role]}
    for key, block_role, heading, body in blocks:
        if block_role is not None and block_role != ROLES[role]:
            continue
        if block_role is None and key in own:
            continue  # this role has its own wording
        if heading:
            lines += [f"### {heading}", ""]
        lines += [body, ""]
    lines += [END, "", ""]
    return "\n".join(lines)


def updated(page: str, block: str) -> str:
    page = BLOCK.sub("\n", page)
    children = CHILDREN.search(page)
    if children is None:
        sys.exit("desktop-privacy: no Children section to put the block in front of")
    return page[: children.start()] + block + page[children.start():]


def main() -> None:
    check = "--check" in sys.argv
    stale = []
    for role in ROLES:
        for suffix, lang in LANGS:
            path = PAGES / role / f"index{suffix}.md"
            current = path.read_text(encoding="utf-8")
            new = updated(current, render(lang, role))
            if new == current:
                continue
            stale.append(str(path.relative_to(ROOT)))
            if not check:
                path.write_text(new, encoding="utf-8")
    if check:
        if stale:
            sys.exit("desktop-privacy: stale — run `make desktop-privacy`: " + ", ".join(stale))
        print("desktop-privacy: the privacy pages match hecate-meta")
    else:
        print(f"desktop-privacy: {len(stale)} page(s) rewritten")


if __name__ == "__main__":
    main()
